name: Frontend Tests

on: 
  pull_request:
    paths:
      - 'src/**'

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16.13"]
    steps:
      - uses: actions/checkout@v3
      
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setting up node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Installing dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Running eslint test
        working-directory: src
        run: yarn lint . --ext .ts,.tsx

      - name: Running jest tests
        working-directory: src
        run: yarn test
