name: Frontend Tests

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn install
      - name: Running eslint test
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: 'src/'
      - name: Running eslint test
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: 'src/'
      - name: Running jest tests
        working-directory: src/utils
        run: yarn test
