name: Frontend Tests

on: [pull_request]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16.13"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Running eslint test
        working-directory: src
        run: yarn lint . --ext .ts,.tsx

      - name: Running jest tests
        working-directory: src
        run: yarn test
